### ISSUE TITLE
Question about MOCHA

### ISSUE THREAD

**Issue by Sherrylife** [omarfoq/FedEM#5]
Hi, @omarfoq, in the openreview(https://openreview.net/forum?id=YCqx6zhEzRp), you say that you implement the MOCHA algorithm in python and experimented with it. Can you updata this part of the code to your repository? I hace been implementing the MOCHA algorithm recently, but I am confused about the SDCA update part in the official matlab source code. I would like to see your implementation. Thank you very much!

**Comment by omarfoq** [comment]
Hello @Sherrylife, 

I share this [notebeook](https://colab.research.google.com/drive/1yN1GAnnjIgu0MeSFizjGF4tBSakBrRdi?usp=sharing) with my implementation of MOCHA. I tried to follow the [official code](https://github.com/gingsmith/fmtl.git), originally written in Matlab, in my implementation. Note however that this is an **unofficial implementation**.

I previously tried to incorporate Mocha in this repository, but I find  its integration hard, as the logic of implementation differs a lot form the general structure of the code provided in [FedEM](https://github.com/omarfoq/FedEM.git). Instead, I will add the link of the notebook in the `README.md` file.

I hope this implementation is of some assistance to you. In case you spot any error, or have additional questions, please don't hesitate to ping me.

**Comment by Sherrylife** [comment]
> Hello @Sherrylife,
> 
> I share this [notebeook](https://colab.research.google.com/drive/1yN1GAnnjIgu0MeSFizjGF4tBSakBrRdi?usp=sharing) with my implementation of MOCHA. I tried to follow the [official code](https://github.com/gingsmith/fmtl.git), originally written in Matlab, in my implementation. Note however that this is an **unofficial implementation**.
> 
> I previously tried to incorporate Mocha in this repository, but I find its integration hard, as the logic of implementation differs a lot form the general structure of the code provided in [FedEM](https://github.com/omarfoq/FedEM.git). Instead, I will add the link of the notebook in the `README.md` file.
> 
> I hope this implementation is of some assistance to you. In case you spot any error, or have additional questions, please don't hesitate to ping me.

Wow! Thank you very much. I will review your code and get back to you as soon as possible.

**Comment by Sherrylife** [comment]
Hi, @omarfoq , I have read your notebook and run it successfully, and there is a tiny error in your notebook, which is highlighted in red in the figure("t" should be changed to "tt"). But it doesn't seem to affect the final result.
![image](https://user-images.githubusercontent.com/60345931/179519394-ab42285f-99fb-4bc5-a0a3-4bf00d4c3bfe.png)
However, frustratingly, I still can't understand a few key updates in SDCA. I have sent an e-mail to the original author to ask her for some details. Unfortunately, maybe the original author was too busy to ignore my letter, but I really want to know some details about MOCHA. So I take the liberty of sending that email to you as well, I assure you that I came to you for help on my own reflection. Can you help me?

**Comment by omarfoq** [comment]
Hi, 

Yes sure. Please send me a message on my email address (othmane.marfoq@inria.fr). In case I can help answering your question, I will do.

Also, since this topic is far from the objective of of this repository, I suggest we close this issue. Please, don't hesitate to open an issue, if something is still unclear for you.
