### ISSUE TITLE
How to use make_plot function in utils/plots.py?

### ISSUE THREAD

**Issue by jxthyatt** [omarfoq/FedEM#8]
Hi, thanks for your work!
Could you release script to use make_plot function in utils/plots.py? Looking forward it.

**Comment by omarfoq** [comment]
Hello @jxthyatt,

[here](https://colab.research.google.com/drive/1xW8aSxv8jfxWvvDwlVCl3WjFaJzcGdOt?usp=sharing) is the link to the collab notebook that I have used to generate the plots. Please let me know, if you have any issues running it.

**Comment by jxthyatt** [comment]
emmm....I fail to visit google, so is there any other way to get the code？

**Comment by omarfoq** [comment]
I am sorry, I don't understand your last message. Do you mean that the link is not working? I have just tested it, and it is working for me. Could you please try it again? Please let me know if the problem persists; I can send you the source code directly.

**Comment by jxthyatt** [comment]
The link is working, but I cannot connect to it.
Please send source code directly to my e-mail jin_xiating@zju.edu.cn. Thanks a lot!

**Comment by omarfoq** [comment]
I have sent you the `.ipynb` on your email address.
